#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

MUNIN_PLUGINS="
	unbound_histogram
	unbound_hits
	unbound_memory
	unbound_queue
	unbound_int_by_class
	unbound_int_by_flags
	unbound_int_by_opcode
	unbound_int_by_rcode
	unbound_int_by_type
"

# Configuring image specific packages
echo "* Configuring image specific packages.";

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
