#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

ln -nfs /opt/local/lib/munin/plugins/unbound_ unbound_histogram
ln -nfs /opt/local/lib/munin/plugins/unbound_ unbound_hits
ln -nfs /opt/local/lib/munin/plugins/unbound_ unbound_memory
ln -nfs /opt/local/lib/munin/plugins/unbound_ unbound_queue
ln -nfs /opt/local/lib/munin/plugins/unbound_ unbound_int_by_class
ln -nfs /opt/local/lib/munin/plugins/unbound_ unbound_int_by_flags
ln -nfs /opt/local/lib/munin/plugins/unbound_ unbound_int_by_opcode
ln -nfs /opt/local/lib/munin/plugins/unbound_ unbound_int_by_rcode
ln -nfs /opt/local/lib/munin/plugins/unbound_ unbound_int_by_type

# Configuring image specific packages
echo "* Configuring image specific packages.";

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
